### ISSUE TITLE
create a selectiontest/cli.py module

### ISSUE THREAD

**Issue by GavinHuttley** [helmutsimon/selectiontest#5]
all your scripts in your current bin directory should be either directly included in this `cli.py` file, or as a separate module in `selectiontest` that is imported by `cli.py`.

In the cli, add the following

```python
import click

@click.group()
def main():
    pass

@main.command()
def calc_TajD(...):
    pass
```

## testing

You need to test the execution of the cl interfaces. [See this example](https://github.com/HuttleyLab/MutationMotif/blob/develop/tests/test_apps.py#L46) for using `click` to facilitate this.

## relocating files

Use `git mv` to do this.” That said, in the case of `calc_TajD`, I'd just remove that file after putting the contents directly into `cli.py`.

Modify your `setup.py`, adding an `entry_points` section ([see this example](https://github.com/helmutsimon/ensembldb3/blob/master/setup.py#L57)). In your case, define your command line app as `neutrality_test` as
```python
    entry_points={
        'neutrality_test': ['ensembldb3=selectiontest.cli:main',
                            ],
```

That way you wind up with a single master command, `neutrality_test`, and all the specific script's you've written are accessible as subcommands, e.g. `$ neutrality_test sample_wf_distribution ...`.

**Comment by helmutsimon** [comment]
Complete except for test code. W

**Comment by helmutsimon** [comment]
Complete except for test code. Will raise new issue for this.
