### ISSUE TITLE
add function for producing SFS

### ISSUE THREAD

**Issue by GavinHuttley** [helmutsimon/selectiontest#6]
Incorporate your `vcf` parsing code to produce the SFS data. It should be a new subcommand (added as a function in `cli.py`), perhaps called `vcf2sfs`, takes vcf input path and a path to write to.

This also means you need to include the `pyvcf` as an `install_requires` in `setup.py`, which also means you need to get a small `vcf` demo file that you can include in your tests.

**Comment by helmutsimon** [comment]
Consider the use of cogent3 generic objects for storing and passing results. See 
https://github.com/cogent3/cogent3/blob/develop/src/cogent3/app/result.py#L24

Also see https://github.com/cogent3/cogent3/blob/develop/tests/test_app/test_result.py#L29 for an example of using / testing the generic result.

**Comment by helmutsimon** [comment]
Added Python module vcf2sfs.

Also added cli function test-neutrality-from-vcf which takes vcf data as input and returns value of rho.
